name: release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable

      - name: build release binary
        run: cargo build --release

      - name: publish immutable release
        uses: ncipollo/release-action@v1.21.0
        with:
          artifacts: target/release/summoning-circle
          generateReleaseNotes: 'true'
          immutableCreate: 'true'
